apps/accounts/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from apps.accounts.views import *

app_name = 'accounts'

urlpatterns = [
    path('signup/', SignUp.as_view(), name="signup"),
    path('users/', UsersView.as_view(), name="users"),
    path('persons/', PersonsView.as_view(), name="persons"),
]

apps/energy_control/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from apps.energy_control.views import *

app_name = 'energy_control'

urlpatterns = [
    path('units/', UnitsView.as_view(), name="units"),
]

scanti/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.home.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('apps.accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('energy_control/', include('apps.energy_control.urls', namespace='energy_control')),
    path('', HomeView.as_view()),
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
        <title>{% block title %}{% endblock title %}</title>
        <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/apple-icon.png' %}">
        <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
        <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
        <link href="{% static 'css/material-dashboard.css' %}" rel="stylesheet" />
        <link href="{% static 'demo/demo.css' %}" rel="stylesheet" />
        {% block css %}{% endblock css %}
        {% block style %}{% endblock style %}
    </head>

    <body class="">
        <div class="wrapper ">
            <div class="sidebar" data-color="rose" data-background-color="black" data-image="{% static 'img/sidebar-1.jpg' %} ">
                <div class="logo">
                    <a href="#" class="simple-text logo-mini"></a>
                    <a href="#" class="simple-text logo-normal">
                        * SCANTI
                    </a>
                </div>
                <div class="sidebar-wrapper">
                    <div class="user">
                        <div class="photo">
                            <img src="{% static 'img/faces/avatar.jpg' %}" />
                        </div>
                        <div class="user-info">
                            <a data-toggle="collapse" href="#" class="username">
                                <span>
                                    {{request.user}}
                                    <!-- <b class="caret"></b> -->
                                </span>
                            </a>
                            <!-- <div class="collapse" id="collapseExample">
                                <ul class="nav">
                                    <li class="nav-item">
                                        <a class="nav-link" href="#">
                                            <span class="sidebar-mini"> P </span>
                                            <span class="sidebar-normal"> Perfil </span>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="#">
                                            <span class="sidebar-mini"> CS </span>
                                            <span class="sidebar-normal">Cerrar sessión </span>
                                        </a>
                                    </li>
                                </ul>
                            </div> -->
                        </div>
                    </div>
                    <ul class="nav">
                        <li class="nav-item active ">
                          <a class="nav-link" href="/">
                              <i class="material-icons">dashboard</i>
                              <p> Dashboard </p>
                          </a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link" href="{% url 'accounts:users' %}">
                                <i class="material-icons"> group </i>
                                <p> Usuarios </p>
                            </a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link" href="{% url 'accounts:persons' %}">
                                <i class="material-icons"> assignment_ind </i>
                                <p> Personas </p>
                            </a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link" href="{% url 'energy_control:units' %}">
                                <i class="material-icons"> all_inbox </i>
                                <p> Unidades </p>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="main-panel">
                <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top " id="navigation-example">
                  <div class="container-fluid">
                      <div class="navbar-wrapper">
                          <div class="navbar-minimize">
                              <button id="minimizeSidebar" class="btn btn-just-icon btn-white btn-fab btn-round">
                                  <i class="material-icons text_align-center visible-on-sidebar-regular">more_vert</i>
                                  <i class="material-icons design_bullet-list-67 visible-on-sidebar-mini">view_list</i>
                              </button>
                          </div>
                          <a class="navbar-brand" href="/admin">ADMIN</a>
                      </div>
                      <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation" data-target="#navigation-example">
                          <span class="sr-only">Toggle navigation</span>
                          <span class="navbar-toggler-icon icon-bar"></span>
                          <span class="navbar-toggler-icon icon-bar"></span>
                          <span class="navbar-toggler-icon icon-bar"></span>
                      </button>
                      <div class="collapse navbar-collapse justify-content-end">
                          <ul class="navbar-nav">
                              <li class="nav-item">
                                  <a class="nav-link" href="#">
                                      <i class="material-icons">dashboard</i>
                                      <p class="d-lg-none d-md-block">
                                          Stats
                                      </p>
                                  </a>
                              </li>
                              <li class="nav-item dropdown">
                                  <a class="nav-link" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                      <i class="material-icons">person</i>
                                      <p class="d-lg-none d-md-block">
                                          Account
                                      </p>
                                  </a>
                                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                                      <a class="dropdown-item" href="{% url 'logout' %}">Perfil</a>
                                      <a class="dropdown-item" href="{% url 'logout' %}">Cerrar Sessión</a>
                                  </div>
                              </li>
                          </ul>
                      </div>
                  </div>
                </nav>
                <div class="content">
                    <div class="container-fluid">
                      {% block content %}
                      {% endblock content %}
                    </div>
                </div>
                <footer class="footer">
                    <div class="container-fluid">
                        <div class="copyright float-right">
                            &copy;
                            <script>
                                document.write(new Date().getFullYear())
                            </script>, copyright SCANTI
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script type="text/javascript" src="{% static 'js/core/jquery.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/core/popper.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/core/bootstrap-material-design.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/plugins/chartist.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/material-dashboard.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'demo/demo.js' %}"></script>
        {% block js %}{% endblock js %}
        <script>
          $(document).ready(function() {
            md.initDashboardPageCharts();
          });
        </script>
        {% block scripts %}{% endblock scripts %}
    </body>

</html>